# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    crm.servicios_controller:
        class:        system\crmBundle\Controller\ServiciosController
        arguments:    ["@doctrine"]
    crm.upload_listener:
        class: system\crmBundle\EventListener\UploadListener
        arguments: ["@doctrine", '%kernel.root_dir%']
        tags:
            - { name: kernel.event_listener, event: oneup_uploader.post_persist, method: onUpload }
    crm.locale_listener:
        class:        system\crmBundle\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }